version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eats
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.eats.monolito:/var/lib/mysql
    ports:
      - "3307:3306"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9410:9410"
      - "9411:9411"


volumes:
  mysql.eats.monolito: