version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eats
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.eats.monolito:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql.eats.monolito: